import "./main.css";
import "../components/x-app.js";
import PouchDB from "pouchdb/dist/pouchdb.js";
import Auth from "pouchdb-authentication/dist/pouchdb.authentication.js";
import * as R from "ramda/es/index.js";
import { Router } from "@vaadin/router";
import * as d3 from "d3";
import * as rxjsOperators from "rxjs/operators";
import * as rxjs from "rxjs";
import * as Redux from "redux/es/redux";
import { persistentStore } from "redux-pouchdb";
import { persistentReducer } from "redux-pouchdb";
import logger from "redux-logger";
import math from "mathjs";
import Chart from "chart.js";
import * as firebase from "firebase";
// var app = firebase.initializeApp({ ... });
import UniversalRouter from "universal-router";
console.log(UniversalRouter);
